### ISSUE TITLE
Warning: The lock file is not up to date with the latest changes in composer.json

### ISSUE THREAD

**Issue by VitoVan** [easychen/mmdcomic#1]
[mmdcomic]$ composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
**Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.**
Nothing to install or update
Generating autoload files

Not familiar with PHP, but should this warning be eliminated ?

**Comment by VitoVan** [comment]
run `composer update` before `composer install --no-dev` seems solved this problem.

**Comment by easychen** [comment]
remove lock file
